# SPDX-FileCopyrightText: 2026 OpenCatastrophe contributors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(python)"
